oiax/tgweb

README.md, packages/tgweb/CHANGELOG.md, packages/tgweb/lib/tgweb/generate_html.mjs, packages/tgweb/lib/tgweb/generation_funcs.mjs, packages/tgweb/lib/tgweb/get_site_data.mjs, packages/tgweb/lib/tgweb/get_type.mjs, packages/tgweb/lib/tgweb/update.mjs, packages/tgweb/package.json, packages/tgweb/test/examples/site_1/src/articles/blog/_wrapper.html, packages/tgweb/test/examples/site_1/src/articles/blog/a.html, packages/tgweb/test/examples/site_1/src/articles/blog/b.html, packages/tgweb/test/examples/site_1/src/articles/blog/c.html, packages/tgweb/test/examples/site_1/src/articles/blog/d.html, packages/tgweb/test/examples/site_1/src/pages/_wrapper.html, packages/tgweb/test/examples/site_1/src/pages/about.html, packages/tgweb/test/examples/site_1/src/pages/index.html, packages/tgweb/test/examples/site_2/src/articles/_wrapper.html, packages/tgweb/test/examples/site_2/src/articles/foo/_wrapper.html, packages/tgweb/test/examples/site_2/src/articles/foo/bar/baz.html, packages/tgweb/test/examples/site_2/src/layouts/home.html, packages/tgweb/test/examples/site_2/src/layouts/normal.html, packages/tgweb/test/examples/site_2/src/pages/etc/_wrapper.html, packages/tgweb/test/examples/site_2/src/pages/etc/about.html, packages/tgweb/test/examples/site_2/src/pages/index.html, packages/tgweb/test/tgweb/generate_html.test.mjs, packages/tgweb/test/tgweb/get_site_data.test.mjs, packages/tgweb/test/tgweb/update.test.mjs
* src/pages/**/_wrapper.html
* src/articles/**/_wrapper.html
=> Introduce wrapper templates

package-lock.json, packages/tgweb/CHANGELOG.md, packages/tgweb/lib/tgweb/get_site_data.mjs, packages/tgweb/lib/tgweb/get_type.mjs, packages/tgweb/lib/tgweb/update.mjs, packages/tgweb/package.json, packages/tgweb/test/examples/site_1/src/components/hello.html, packages/tgweb/test/examples/site_1a/src/components/hello.html, packages/tgweb/test/examples/site_1a/src/pages/_wrapper.html, packages/tgweb/test/tgweb/get_site_data.test.mjs, packages/tgweb/test/tgweb/update.test.mjs
Fix updateSiteData/2: process front matters
Update all pages and articles when site.yml gets updated
=> Update pages and articles correctly

packages/tgweb/lib/init.mjs
Following commit @kuroda created, includes the line.
https://github.com/pojiro/teamgenik_pub_samples/commit/6d6b6bba44943cdb4ce22fd5ee088b6b4fffdc37#diff-bc37d034bad564583790a46f19d807abfe519c5671395fd494d8cce506c42947R4
So i added too.
=> Add `/sites/*/tailwind.config.js` to gitignore which is generated by `tgweb-init`

package-lock.json, packages/tgweb/CHANGELOG.md, packages/tgweb/lib/tgweb/create.mjs, packages/tgweb/package.json
* b0fc697 Bug fix: Added images/audios are not copied into dist directory
=> v0.5.1 dev

package-lock.json, packages/tgweb/CHANGELOG.md, packages/tgweb/lib/tgweb/render_web_page.mjs, packages/tgweb/package.json, packages/tgweb/resources/tgweb_utilities.js
* 6987825 Make carousel paginator scroll smoothly
Close #83
=> v0.5.3 dev

README.md
=> Update content to current version

README-ja.md
Translate first 4 sections.
Closed #87
=> Translate README.md to Japanese

package-lock.json, packages/tgweb/CHANGELOG.md, packages/tgweb/lib/server/router.mjs, packages/tgweb/package.json
=> Merge v0.5.5-dev

package-lock.json, packages/tgweb/CHANGELOG.md, packages/tgweb/lib/server/router.mjs, packages/tgweb/package.json
=> Merge v0.5.6-dev

README-ja.md
README-ja.mdの「ページ」の部分を日本語に翻訳しました。
レビューをお願いいたします。
close #126
=> Translate README-ja.md on Pages to Japanese

README-ja.md, README.md
README-ja.mdの「フロントマター」の部分を日本語に翻訳しました。
レビューをお願いいたします。
close #128
=> Translate README-ja.md on Front Matter to Japanese

README-ja.md, README.md
README-ja.mdの「画像」の部分を日本語に翻訳しました。
レビューをお願いいたします。
close #135
=> Translate README-ja.md on Images to Japanese

README-ja.md
README-ja.mdの「音声」の部分を日本語に翻訳しました。
レビューをお願いいたします。
close #136
=> Translate README-ja.md on Audios to Japanese

README-ja.md, README.md
README-ja.mdの「フォントとアイコン」の部分を日本語に翻訳しました。
レビューをお願いいたします。
close #139
=> Translate README-ja.md on Fonts and Icons to Japanese

README-ja.md, README.md
「フォントとアイコン」の「異体」に関する箇所を翻訳しました。
レビューをお願いいたします。
close #139
=> Translate README-ja.md on Variants in the Fonts and Icons section to Japanese

README-ja.md, README.md
README-ja.mdの「レイアウト」の部分を日本語に翻訳しました。
また、README.md も少し変更しました。
レビューをお願いいたします。
close #141
=> Translate README-ja.md on Layouts to Japanese

README-ja.md, README.md
README-ja.mdの「ラッパー」の部分を日本語に翻訳しました。
また、サンプルを含めて内容を少し変更しました。
レビューをお願いいたします。
close #145
=> Translate README-ja.md on Wrappers to Japanese

README-ja.md, README.md
README-ja.mdの「部品」の部分を日本語に翻訳しました。
また、README.md についても一部変更しました。
レビューをお願いいたします。
close #153
=> Translate README-ja.md on Components to Japanese

README-ja.md
「ミニアプリの埋め込み」について日本語に翻訳しました。
レビューをお願いいたします。
close #169
=> Translate README-ja.md on Embedding Teamgenik Mini-apps to Japanese

README-ja.md, README.md
修正が完了しましたのでレビューをお願いいたします。
close #187
=> Minor fixes to README.md and README-ja.md

README-ja.md, README.md
Changed the wording of “Variants” to “Icon Variants”.
Please review.
close #211
=> [README] Change the wording of “Variants” to “Icon Variants”
